apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld
  namespace: ocexpertcamp
spec:
  template:
    metadata:
      name: helloworld-v2
      annotations:
        # disable istio-proxy injection
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - image: docker.io/fliegera/helloworld:v1
        env:
        - name: MESSAGE_PREFIX
          value: Namaste
        livenessProbe:
          httpGet:
            path: /healthz
        readinessProbe:
          httpGet:
            path: /healthz
  traffic:
  - tag: current
    revisionName: helloworld-v1
    percent: 100
  - tag: prev
    revisionName: helloworld-v2
    percent: 0
  - tag: latest
    latestRevision: true
    percent: 0 
