apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: event-helloworld-subscriber
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: ch-event-helloworld
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: event-helloworld
