apiVersion: sources.eventing.knative.dev/v1alpha1
kind: CronJobSource
metadata:
  name: event-helloworld-cronjob-source
spec:
  schedule: "* * * * *"
  data: '{"message": "Thanks for doing Knative Tutorial"}'
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: ch-event-helloworld
